version: '3.8'

services:

  db:
    image: postgres:15.1
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - traefik_default
    ports:
      - "5432:5432"
    restart: always

  web:
    build: .
    command: bash -c "sleep 5 && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --reload"
    container_name: imageapp
    networks:
      - traefik_default
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - env_file_path=docker.env
    depends_on:
      - db
    restart: always

networks:
  traefik_default:
    external: true
