"""empty message

Revision ID: 06e053f7b973
Revises: c885780d2735
Create Date: 2023-01-14 00:21:54.981606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e053f7b973'
down_revision = 'c885780d2735'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
