"""Created Image model

Revision ID: 337891cbe37a
Revises: cd3ae5387fc6
Create Date: 2023-01-14 00:10:28.719520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337891cbe37a'
down_revision = 'cd3ae5387fc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
