"""empty message

Revision ID: 7b868ac22669
Revises: 06e053f7b973
Create Date: 2023-01-14 00:23:38.419297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b868ac22669'
down_revision = '06e053f7b973'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
