"""empty message

Revision ID: d456b8d1a2fd
Revises: 7b868ac22669
Create Date: 2023-01-14 00:26:13.978217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd456b8d1a2fd'
down_revision = '7b868ac22669'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
